
all: ca admin kubelet kube-proxy api-server

ca:
	./ca/ca.sh

admin:
	./admin/admin.sh

kubelet:
	./kubelet/kubelet.sh

kube-proxy:
	./kube-proxy/kube-proxy.sh

api-server:
	./api-server/api-server.sh

distribute:
	./distribute-certs.sh

